### PR TITLE
Transporter option, enhanced template rendering, additional improvements

### PR DESCRIPTION
**Pull request by dapriett**
- Added a transporter option to allow passing your own custom transporter directly to nodemailer.createTransport
- If using service/auth params, wrap with the smtp-pool-transport
- Changed template rendering to use the built in sails.hooks.views.render method to get the benefit of allowing other template engines as well as layouts.  If Sails View hook is disabled, fallback to ejs template engine
- Added nodemailer-html-to-text plugin to allow auto generate of mail text from html if not provided.
- Updated docs

### CODE REVIEW

**Comment by tcury** [comment]
+1 nice PR

**Comment by sgress454** [comment]
@dapriett looking good!  Could you:
1. Remove the changes to .gitignore
2. Revert the whitespace changes to index.js so we can see the actual changes?  I think you have tabs set to 4 spaces instead of two.  I added an .editorconfig file if that helps.

Thanks!

**Comment by dapriett** [comment]
@sgress454 Just made the changes, let me know if that looks better.

**Comment by tcury** [comment]
Any status for this merge?

**Comment by sgress454** [comment]
Sorry, been a little underwater with Sails PRs, will get to this ASAP.

**Comment by sgress454** [comment]
@dapriett Merged, and invited you to a team so I can add you as a collaborator on this repo if you're game...

**Comment by dapriett** [comment]
@sgress454 Sounds good, thanks for the merge and the invite.

**Pull request merged**
