### PR TITLE
Upgraded Nodemailer, added new options, moved to Sails View Engine

### PR DESCRIPTION
**Pull request by dapriett**
I made the following changes to sails-hook-email:
- Upgraded to `nodemailer 1.3.4`
- Added a `global` option for creating a global method for sending mail
- Added a `transporter` option to allow passing your own custom transporter directly to nodemailer.createTransport
- Changed template rendering to use the built in sails.hooks.views.render method to get the benefit of allowing other template engines

### CODE REVIEW

**Comment by tcury** [comment]
+1 to merge it. I need to test with SES transport.

**Comment by sgress454** [comment]
@dapriett I ended up merging #8, but feel free to rebase and/or submit another PR.  

I'm open to the hook being able to handle more than just .ejs files, but I'd rather not make it dependent on the Sails views hook, since that can be turned off.  You could use a solution that incorporates Consolidate.js, like the views hook does.

Re: the global mail option, I would leave that out.  The end user can choose to add a global or not to their app which points to sails.hooks.email.sendEmail, but it's not something an option that belongs in the hook itself.

**Comment by dapriett** [comment]
@sgress454 

Cool - I can remove the global option.  

Is there a way to disable the sails view hook?  It seems like it's currently embedded in the sails module.  I figured using that directly would reduce having to configure your template engines in multiple place.  I could also just fallback to ejs if for some reason the sails hook is not there.

It looks like in the branch you merged it's passing the options directly to the createTransport method.  We may want to make it a separate option - so you can do stuff like this:

```
var smtpPool = require('nodemailer-smtp-pool');

module.exports.mailer = {
    testMode: false,

    from: "noreply@internet.com",

    transporter: smtpPool({
            host: 'localhost',
            port: 25,
            auth: {
             user: 'username',
              pass: 'password'
           },
           // use up to 5 parallel connections
           maxConnections: 5,
         // do not send more than 10 messages per connection
          maxMessages: 10,
          // no not send more than 5 messages in a second
          rateLimit: 5
        })
}
```

Otherwise currently in order to set sails-hook-email options (such as from, alwaysSendTo, etc) we would have to create the smtpPool object and then inject the hook options directly into it.

Also currently the old way (just providing service & auth) doesn't do pooling anymore like it used to.  You have to explicitly wrap it in an smtpPool transport now with the new version.  My branch handles that, so I can try to rebase and merge that in as well.

**Comment by tcury** [comment]
Yea. I agree. I don't know how to merge these two objects:
```
var ses = require('nodemailer-ses-transport');
module.exports = {
  email: ses({
    accessKeyId: 'xxx',
    secretAccessKey: 'xxx'
  }),
  email: {
    from: 'xx@xx.com',
    testMode: false
  },
```

**Comment by tcury** [comment]
I got it injecting the two parameters in the end of file:
```
module.exports.email.from = 'xx@xx';
module.exports.email.testMode = false; 
```

**Comment by dapriett** [comment]
I rebased and created a new pull request: https://github.com/balderdashy/sails-hook-email/pull/15 with the following improvements
- Added a transporter option to allow passing your own custom transporter directly to nodemailer.createTransport
- If using service/auth params, wrap with the smtp-pool-transport
- Changed template rendering to use the built in sails.hooks.views.render method to get the benefit of allowing other template engines as well as layouts. If Sails View hook is disabled, fallback to ejs template engine
- Added nodemailer-html-to-text plugin to allow auto generate of mail text from html if not provided.
- Updated docs

**Pull request closed without merging**
